### PR TITLE
update etcd to version v3.4.0

### PR DESCRIPTION
**Pull request by szuecs**
Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

### CODE REVIEW

**Comment by szuecs** [comment]
Hmm @CyberDem0n V3API has a lot of improvements and we only use v3api since more than a year.
Do you think you would migrate to v3api?

**Comment by CyberDem0n** [comment]
[etcd.py](https://github.com/zalando-stups/stups-etcd-cluster/blob/master/etcd.py) is using v2 API in order to get and change cluster topology (member list/add/remove).
It is not doing that many calls therefore performance is not critical.
I am not sure that changing the code in order to start supporting v3 is worth the time spent on it.

For now we can just conditionally add `--enable-v2` argument like we already doing so with `-listen-metrics-urls` [here](https://github.com/zalando-stups/stups-etcd-cluster/blob/master/etcd.py#L274).
That will make it alive until v2 is completely ditched from the etcd codebase.

**Comment by szuecs** [comment]
Should we also add somewhere a link to the upgrade checklist? 
https://github.com/etcd-io/etcd/blob/master/Documentation/upgrades/upgrade_3_4.md#upgrade-checklists

**Comment by szuecs** [comment]
https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/runtime-configuration.md#add-a-new-member-as-learner is also interesting to change to a more safe `member add` process

**Comment by CyberDem0n** [comment]
> is also interesting to change to a more safe member add process

Agree, but that probably requires v3 API :(

**Comment by aermakov-zalando** [comment]
Are there any other changes needed?

**Comment by CyberDem0n** [comment]
No, but one should really try to upgrade 3.3 => 3.4 when the image is ready.

**Comment by CyberDem0n** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
